#!/bin/sh

auth=$AUTH
user=$USER
cpu=$CPU

while :; do
	case $1 in
		-a)
			auth=$2
			shift
			;;
		-u)
			user=$2
			shift
			;;
		-h)
			cpu=$2
			shift
			;;
		*)
			break;
	esac
	shift
done

cmd="rc -i"

if [ "$#" -ne 0 ]; then
	cmd=$*
fi

USER=$user AUTH=$auth CPU=$cpu tlsclient -R -p 17019 $cmd
