#!/bin/sh

auth=$AUTH
user=$USER
cpu=$CPU

while :; do
	case $1 in
		-a)
			auth=$2
			shift
			;;
		-u)
			user=$2
			shift
			;;
		-h)
			cpu=$2
			shift
			;;
		*)
			break;
	esac
	shift
done

cmd="rc -i"

if [ "$#" -ne 0 ]; then
	cmd=$*
fi

len=`echo $cmd | wc -c`

cmd=`cat <<EOF
printf '%7d\n' $len;
echo $cmd;
cat </dev/tty 2>/dev/null &
cat >/dev/tty 2>/dev/null;
EOF
`
USER=$user AUTH=$auth CPU=$cpu tlsclient -p 17019 sh -c "$cmd"
