.Dd July 20, 2023
.Dt MOUNT.9PTLS 8
.Os tlsclient
.
.Sh NAME
.Nm mount.9ptls
.Nd tlsclient mount helper
.Sh SYNOPSIS
.Nm
.Op Fl sfnvh
.Op Fl N Ar namespace
.Op Fl o Ar options
.Ar fileserver
.Ar mountpoint
.
.Sh DESCRIPTION
The
.Nm
helper is used by
.Xr mount 8
to wrap a 9p filesystem through a dp9ik authenticated
tls tunnel provided by
.Xr tlsclient 1 .
This is accomplished by interpreting the arguments provided,
setting up the connection and then passing the file descriptors
to the kernel 9p mount.
.Ar Fileserver
is connected to over TCP, doing DNS resolution as required.
As there is no standard port for this type of service a
.Fl o Ar port
option is required.
.
.Sh OPTIONS
The following
.Ar options
are ingested by
.Nm :
.Bl -tag -width "-o xa"
.It Ar port
The TCP port to connect to the
.Ar filserver
on.
.It Ar auth
The shared 9front authentication server to use between
.Nm
and the
.Ar fileserver .
.It Ar askpass
The program that is executed to prompt the user for their password.
If this is not specified it defaults to
.Xr systemd-ask-password 1 .
.El
.Pp
All remaining flags and
.Ar options
are preserved as-is and passed along to the resulting 9p fs
mount call.
.
.Sh SEE ALSO
.Xr tlsclient 1 ,
.Xr fstab 5 ,
.Xr mount 8
